# Generated by Django 4.1.4 on 2022-12-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=225)),
                ('cpf', models.CharField(max_length=15)),
                ('idade', models.IntegerField()),
                ('turma', models.CharField(max_length=50)),
                ('matricula', models.IntegerField()),
            ],
        ),
    ]
